# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e109927b19b06a0588235e45c388e7fe39f238bcaf9ecff0e5fdc190d6fea1451ccc7393940b90941cfe828a7ae047cc8d155dc77f7965c28cfd220695a5ad3

test:
  secret_key_base: 34a37ec2d7e292225fc096e45b08d7531cbff0dbecb2a547b22f8adaeb41aa589b9352e0baf4176840e6974f37d9e485eb4faf5710aceb238a0743516b0e8d48

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
